use crate::metadata::ir::*;
pub(crate) static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Pwr",
        extends: None,
        description: Some("Power control."),
        items: &[
            BlockItem {
                name: "ctlr",
                description: Some("power control register."),
                array: None,
                byte_offset: 0x0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctlr"),
                }),
            },
            BlockItem {
                name: "csr",
                description: Some("power control/status register."),
                array: None,
                byte_offset: 0x4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Csr"),
                }),
            },
            BlockItem {
                name: "awucsr",
                description: Some("auto-wakeup control/status register."),
                array: None,
                byte_offset: 0x8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Awucsr"),
                }),
            },
            BlockItem {
                name: "awuwr",
                description: Some("auto-wakeup window comparison value register."),
                array: None,
                byte_offset: 0xc,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Awuwr"),
                }),
            },
            BlockItem {
                name: "awupsc",
                description: Some("auto-wakeup prescaler register."),
                array: None,
                byte_offset: 0x10,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Awupsc"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Awucsr",
            extends: None,
            description: Some("auto-wakeup control/status register."),
            bit_size: 32,
            fields: &[Field {
                name: "awuen",
                description: Some("Auto-wakeup enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Awupsc",
            extends: None,
            description: Some("auto-wakeup prescaler register."),
            bit_size: 32,
            fields: &[Field {
                name: "awupsc",
                description: Some("Auto-wakeup counter prescaler."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 4,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Awuwr",
            extends: None,
            description: Some("auto-wakeup window comparison value register."),
            bit_size: 32,
            fields: &[Field {
                name: "awuwr",
                description: Some("Auto-wakeup window value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 6,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Csr",
            extends: None,
            description: Some("power control/status register."),
            bit_size: 32,
            fields: &[Field {
                name: "pvdo",
                description: Some("PVD output flag."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ctlr",
            extends: None,
            description: Some("power control register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pdds",
                    description: Some("Power-down deep sleep selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldo_mode",
                    description: Some("Voltage regulator operating mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pvde",
                    description: Some("Power voltage detector enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pls",
                    description: Some("PVD voltage threshold selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "flash_lp_reg",
                    description: Some("Flash low-power mode enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "flash_lp",
                    description: Some("Flash low-power configuration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
